REGION_NAME = "us-east-1"
AWS_ACCESS_KEY_ID = "AKXXXXXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
# os.environ['AWS_ACCESS_KEY_ID'] export AWS_ACCESS_KEY_ID = 
# os.environ['AWS_SECRET_ACCESS_KEY'] export AWS_SECRET_ACCESS_KEY = 