REGION_NAME = "us-east-1"
SECURITY_GROUP_ID = ["sg-0bb98ead470e1d287"]
APP_TIER_AMI = "ami-0a55e620aa5c79a24"
INSTANCE_TYPE = 't2.micro'
AWS_ACCESS_KEY_ID = "AKXXXXXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
# os.environ['AWS_ACCESS_KEY_ID'] export AWS_ACCESS_KEY_ID = 
# os.environ['AWS_SECRET_ACCESS_KEY'] export AWS_SECRET_ACCESS_KEY = 